<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2012 University of Luxembourg and others.
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
  
  Contributors:
      Max E. Kramer - initial API and implementation
-->
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defaultname"
    nsURI="http://defaultname/1.0" nsPrefix="defaultname">
  <eClassifiers xsi:type="ecore:EClass" name="IfcWindow"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfcWindowStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//IfcWindowStyle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//IfcWindowStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConstructionType = IfcWindowStyleConstructionEnum.HIGH_GRADE_STEEL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfcBuildingStorey">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Elevation = 0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfcRelContainedInSpatialStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelatedElements" eType="#//IfcWindow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelatingStructure" eType="#//IfcBuildingStorey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfcRelDefinesByType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelatedObjects" eType="#//IfcWindow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelatingType" eType="#//IfcWindowStyle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructionType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="IfcWindowStyleConstructionEnum">
    <eLiterals name="HIGH_GRADE_STEEL"/>
  </eClassifiers>
</ecore:EPackage>
