<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2012 University of Luxembourg and others.
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
  
  Contributors:
      Max E. Kramer - initial API and implementation
-->
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lts_av"
    nsURI="http://lts_advice" nsPrefix="lts_av">
  <eAnnotations/>
  <eClassifiers xsi:type="ecore:EClass" name="LTS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedState" ordered="false"
        upperBound="-1" eType="#//State" containment="true" eOpposite="#//State/owningLTS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" ordered="false"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalState" ordered="false"
        upperBound="-1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningLTS" eType="#//LTS"
        eOpposite="#//LTS/ownedState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransition" ordered="false"
        upperBound="-1" eType="#//Transition" containment="true" eOpposite="#//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransition" ordered="false"
        upperBound="-1" eType="#//Transition" eOpposite="#//Transition/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//State"
        eOpposite="#//State/outgoingTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"
        eOpposite="#//State/incomingTransition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Advice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
